.c.o:   $*.h
	gcc -c $*.c

.cpp.o:	$*.h
	g++	-c $*.cpp

all:	trabalho

trabalho:  trabalho.o Triangulacao.o opGeometricas.o winGL.o 
	gcc -o $@ $^ -lglut32 -lopengl32 -lglu32

clean:
	rm *.o *.*~ *~ trabalho